---
vector_version: "0.33.0"
vector_architecture: "x86_64"
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
vector_config_dir: "/etc/vector"
vector_config:
  sources:
    demo_logs:
      type: demo_logs
      format: json
      interval: 0.1
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - demo_logs
      database: logs
      endpoint: 127.0.0.1
      table: vector_table
      compression: gzip
      healthcheck: true
      skip_unknown_fields: true